### ISSUE TITLE
Alignment Issues

### ISSUE THREAD

**Issue by JasmineCT** [JasmineCT/portfolio#5]
There are two issues I am having:
1. In my specialties section the boxes are not aligning to the middle. There are some weird spacing on the right side and it is not centring them on the screen sizes. Not sure how to target them all, I do have a width on the cards to prevent them from collapsing. 

2. On my index page the bw quote image and the connection section don't see to be aligning. The image covers the connection section as if the relative class isn't doing anything. Not sure how to fix this without causing the quote to jump around.

@thomasjbradley

**Comment by thomasjbradley** [comment]
1. I think it must be because of the `height`, `width` & `margin` on `.card`—they are conflicting with the grid unit sizes.

2. I can’t see your index page, have you committed & pushed?

**Comment by JasmineCT** [comment]
I try to push but I get this error
<img width="807" alt="Screen Shot 2019-11-18 at 7 28 09 PM" src="https://user-images.githubusercontent.com/31959259/69193800-9cabee00-0af5-11ea-8504-6c9ef538761d.png">
@thomasjbradley

**Comment by thomasjbradley** [comment]
Uh oh. I can’t fix that remotely. I’ll have to do it in class.
