### ISSUE TITLE
Netlify website not updating

### ISSUE THREAD

**Issue by JasmineCT** [JasmineCT/portfolio#6]
When I go on my local host my website it up to date and working normally. But when I go to the netlify website its almost like it hasn't updated. It still has to small boxes of my specialties and none of the pages are linking properly (on my netlify page only).

Any suggestions on why this isn't working?
@thomasjbradley

**Comment by thomasjbradley** [comment]
Nothing I can see from here. I’ll have to look at the Netlify build logs in your account.
