### ISSUE TITLE
Browser Testing + Portfolio Fixes + Accessibility testing

### ISSUE THREAD

**Issue by JasmineCT** [JasmineCT/portfolio#7]
I did some accessibility testing and noticed some issues:
- On Opera the specialties boxes that lead to the case studies are getting cut off, run into some awkward alignment issues.
~ This was fixed by added a new grid size, and going back and fixing the medium and large sizes to be 1/2 while extra large and xxl are 1/4
- Mobile size on iPhone 7 works, some images load longer (not sure if this is due to my netlify not updating), however the quote image and quote over the image seems small and it cutting off the connect section.
~ Again not sure if this is due to netlify not updating, but this is fixed by making the font larger for more readability.
- Safari wasn't tabbing through the header or footer, and buttons.
  ~ This issue was fixed by fixing my accessibility settings on my safari browser
- On my quote section on the index page, on normal large screens (my mac book) the text was to large for the screen and causing some reading issues.
   ~This issue was fixed by changing the font size for the large screen size, making it smaller in the media query 
- Images were taking longer to load on the page 
   ~This issue was solved by going into photoshop and reducing the size and quality of the images, and finally putting them through the Imgoptim.
- The specializing section showing boxes with titles and buttons to read more about case studies were getting cut off due to lack of screen space on large and medium screen sizes. 
   ~This was fixed by adding a new grid size and fixing the medium screen size to have two on a line to optimize space and readability.
- Aria labels where not set up for voice over
   ~This was fixed by adding Aria labels to images on case studies to have detail descriptions of images
- The forms are not submitting on the home page or on the contact page
   ~This was fixed by adding a new button pattern for just the submitting button, and connecting it through form spree

@thomasjbradley

**Comment by thomasjbradley** [comment]
Did you do browser testing in Microsoft Edge?

**Comment by JasmineCT** [comment]
I did but again my netlify url isn't up to date because the squares are still getting cut off, and none of the pages are linked.

**Comment by thomasjbradley** [comment]
Right. Okay.
